name: Framework
version: ${project.version}
main: gg.steve.mc.framework.framework.Framework
api-version: 1.15.2
authors: [stevegoodhill]
description: Framework that I use for all of my minecraft plugins. NOTE: this is the base repo, in most of my plugins I will make changes to make it work with that plugin.
website: http://steve.gg
